#服务端的开发版本

#tomcat
server:
  port: 8080

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #远程服务器的ip  + 服务器中的mysql所监听的端口 + mysql中数据库名称
    url: jdbc:mysql://47.109.27.38:3306/db_hualian?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #远程服务器的密码
    username: root
    password: Mdh074518#


#mybatis-plus
mybatis-plus:
  configuration:
    #开启驼峰命名的自动转换，将数据库的user_id,匹配Java的userId
    map-underscore-to-camel-case: true
    # 将mybatis的执行过程（sql）打印在控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #所有字段都为空时，返回空对象，而不是null
    return-instance-for-empty-row: true
  mapper-locations: classpath*:mapper/**/*.xml
  #别名所在的包
  type-aliases-package: com.gxa.agriculture.entity.pojo
